Removed curly brace array access for > PHP 7.4 use
As outlined in the RFC - https://wiki.php.net/rfc/deprecate_curly_braces_array_access

array access via curly braces is now deprecated.

And for people searching this issue in the future:

ErrorException: Array and string offset access syntax with curly braces is deprecated in AnimGif.php:206